FROM node:18-alpine AS builder

WORKDIR /app

COPY client/package*.json ./
COPY client/next.config.ts ./
COPY client/tsconfig.json ./
COPY client/postcss.config.mjs ./
COPY client/eslint.config.mjs ./
COPY client/middleware.ts ./

RUN npm install

COPY client/app ./app
COPY client/public ./public

RUN npm run build



FROM node:18-alpine AS runner

WORKDIR /app

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package*.json ./

RUN mkdir -p /app/public/uploads

RUN npm install --omit=dev

EXPOSE 3000

CMD ["npm", "start"]
