filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/transcendence/*.log      # 🔥 logs from shared volume
    processors:
      - add_fields:
          target: 'service'
          fields:
            name: 'transcendence-server'

output.logstash:
  hosts: ["logstash:5044"]
  ssl.certificate_authorities: ["/data/ca/ca.crt"]
  ssl.certificate: "/data/filebeat/filebeat.crt"
  ssl.key: "/data/filebeat/filebeat.key"
