FROM docker.elastic.co/elasticsearch/elasticsearch:8.15.0

USER root

COPY elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
RUN chown elasticsearch:elasticsearch /usr/share/elasticsearch/config/elasticsearch.yml

ENV discovery.type=single-node
ENV ES_JAVA_OPTS="-Xms512m -Xmx512m"
ENV xpack.security.enabled=true
ENV ELASTIC_PASSWORD=changeme

USER elasticsearch
