
import type { Metadata } from "next";
import { Chakra_Petch } from "next/font/google";
import "./globals.css";
import { LayoutComp } from "./components/layoutnavbar";
import { UserProvider } from "./Context/UserContext";
import { NotificationProvider } from "./Context/NotificationContext";
import { PresenceProvider } from "./Context/PresenceContext";
import { AlertContainer } from "./components/Alert";

const chakra = Chakra_Petch({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-chakra",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${chakra.variable} font-chakra min-h-screen`} >
        <UserProvider>
          <NotificationProvider>
            <PresenceProvider>
            <img
              src="/back.webp"
              alt="Logo"
              className="absolute w-full h-full object-cover -z-10"
              style={{ filter: "brightness(0.5) blur(10px)" }}
            />
              <LayoutComp>
                {children}
              </LayoutComp>
            </PresenceProvider>
          </NotificationProvider>
        </UserProvider>
        <AlertContainer />
      </body>
    </html>
  );
}
