FROM prom/prometheus:latest

COPY alert_rules.yml /etc/prometheus/alert_rules.yml

COPY prometheus.yml /etc/prometheus/prometheus.yml

EXPOSE 9090

CMD ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus"]