FROM docker.elastic.co/kibana/kibana:8.15.0

USER root

COPY kibana.yml /usr/share/kibana/config/kibana.yml
COPY dashboard.ndjson /usr/share/kibana/config/dashboard.ndjson
COPY entrypoint.sh /usr/local/bin/custom-entrypoint.sh

RUN chmod +x /usr/local/bin/custom-entrypoint.sh

USER kibana

ENTRYPOINT ["/usr/local/bin/custom-entrypoint.sh"]
