FROM node:18-alpine

WORKDIR /usr/src/app

COPY ./server/package*.json ./

RUN npm install --only=production

COPY ./server ./

RUN rm -rf node_modules && npm install --only=production

RUN mkdir -p /usr/src/app/uploads

CMD ["npm", "start"]
