FROM nginx:alpine

RUN apk add --no-cache openssl

# Generate self-signed certs (valid 1 year)
RUN mkdir -p /etc/nginx/ssl && \
    openssl req -x509 -nodes -days 365 -out /etc/nginx/ssl/trans.crt \
    -keyout /etc/nginx/ssl/trans.key \
    -subj "/C=MO/ST=KH/L=KH/O=1337/OU=1337/CN=10.32.118.247/UID=trans"

COPY ./nginx/conf/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
