FROM docker.elastic.co/kibana/kibana:8.15.0

USER root

COPY kibana.yml /usr/share/kibana/config/kibana.yml
COPY dashboard.ndjson /usr/share/kibana/config/dashboard_template.ndjson
COPY docker-entrypoint.sh /opt/scripts/docker-entrypoint.sh

RUN chmod +x /opt/scripts/docker-entrypoint.sh
RUN chown kibana:kibana /opt/scripts/docker-entrypoint.sh

USER kibana

ENTRYPOINT ["/opt/scripts/docker-entrypoint.sh"]
